package main

import "fmt"

func main() {
	i, j, sum := 0, 1, 0
	for i <= 4000000 {
		i, j = j, i+j
		if i%2 == 0 {
			sum += i
		}
	}
	fmt.Println(sum)
}

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
